# 💥 Primeros pasos con ``Python`` 💥

|| <a style="background-color: #1bf8ff; color: #000000; border: none; padding: 10px 15px; border-radius: 5px;">Introducción a Python</a> ||
<a style="background-color: #1bf8ff; color: #000000; border: none; padding: 10px 15px; border-radius: 5px;">Clase 3</a> ||
<a style="background-color: #1bf8ff; color: #000000; border: none; padding: 10px 15px; border-radius: 5px;">Cursos PyM</a> ||
<a style="background-color: #1bf8ff; color: #000000; border: none; padding: 10px 15px; border-radius: 5px;">Luis Fernando Apáez Álvarez</a> ||

## 🪗 Acordeón 🪗

---

1. Avance del proyecto de clase. Solución a los problemas dejados.
2. Código para generar el dataframe con la información simulada.
3. Introducción a SQL
  * Creación de bases de datos y tablas.
  * Inserciones
  * Consultas

4. Funciones en Python
5. Manejo de fechas con Pandas

In [ ]:
import random as r
import pandas as pd

abcdario = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
            'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
            'U', 'V', 'W', 'X', 'Y', 'Z']

papelerias = ['Xochimilco', 'Cuemanco', 'Coapa', 'Milpa Alta', 'CU', 'Zócalo',
              'Narvarte', 'Santa Fé', 'Polanco', 'Centro']

lineas = ['Cuadernos', 'Libretas', 'Lápices', 'Plumones', 'Borradores', 'Sacapuntas',
          'Laptops', 'Tablets', 'Mochilas', 'Bolsas', 'Cajas', 'Pegamento', 'Tijeras',
          'Monitores', 'Teclados', 'Mouse', 'Audífonos', 'Cables', 'Cargadores', 'Baterías',
          'Pc', 'Uniformes', 'Pinturas', 'Pinceles', 'Papel', 'Cartulinas']

# 1. Avance del proyecto de clase. Solución a los problemas dejados.

###  Objetivo de salida:

```
*****************************************************
Bienvenido a comercializara Zavadeii.
Te atendió Lupillo (sustituye Lupillo por tu nombre).
*****************************************************
* Fecha reporte: 2025-01-04
* Nombre del producto: Libreta (en vez de decir libreta deberás de implementar el código para que se
seleccione un producto de manera aleatoria).
* Precio: $24.00 (en vez de decir 24.00 deberás de implementar el código para que
se genere el precio de manera aleatoria).
* Cantidad: 7 (en vez de decir 7 deberás de implementar el código para que
se genere el nùmero entero de manera aleatoria).
* Clave del producto: AB12-X3 (en vez de decir AB12-X3 deberás de implementar el código para
que se genere de manera aleatoria la clave del producto en el formato solicitado).
* Sucursal: Xochimilco(en vez de decir Xochimilco deberás de implementar el código
para que se seleccione una sucursal de manera aleatoria).
*****************************************************
*****************************************************
```

In [ ]:
ticket = f"""
Fecha: 2025-01-04
Sucursal: {r.choice(papelerias)}
Producto: {r.choice(lineas)}
Clave producto: {r.choice(abcdario) + r.choice(abcdario) + r.choice(abcdario) + "-" + str(r.randint(1,9)) + str(r.randint(1,9)) + str(r.randint(1,9))}
Precio: {round(r.random() * r.randint(100, 10000), 2)}
Cantidad vendida: {r.randint(1, 1000)}
"""

print(ticket)

Fecha: 2025-01-04

Sucursal: Narvarte

Producto: Cuadernos

Clave producto: CIA-952

Precio: 1649.81

Cantidad vendida: 339

### Solución problema 1

In [ ]:
#  herramientas varias, particularmente nos sirve para conteos
from collections import Counter

# a) Realiza la simulaciòn de 100 lanzamientos de una moneda,
# para lo cual deberàs de utilizar el còdigo visto en clase màs el tema referente al bucle for.

moneda = ['Águila', 'Sol']
resultados = []

for i in range(100):
  resultados.append(r.choice(moneda))

# Veamos cuantos soles y aguilas obtuvimos
Counter(resultados)

Counter({'Sol': 53, 'Águila': 47})

### Solución al problema 2

In [ ]:
# Haciendo uso de la funciòn input, del uso de los f-strings (y strings multilìnea),
# del uso de las funciones de conversiòn (como float(), int() o str()), crea una programa que solicite dos datos al usuario:
# su nombre y su edad. Luego, define una variable que se denomine agno_nacimiento como:

nombre = input("¿Cuál es tu nombre? ")
edad = int(input("¿Cuál es tu edad? "))
agno_nacimiento = 2025 - edad

print(f"Hola {nombre}, naciste en el año {agno_nacimiento}")

¿Cuál es tu nombre? Luis
¿Cuál es tu edad? 27
Hola Luis, naciste en el año 1998

### Dataframe con la información simulada

Con base en lo aprendido en clases anteriores, podemos simular la información de ventas de un día.

In [ ]:
# Fecha reporte
fecha = "2025-01-04"

# Definimos listas vacias que almacenaran la informacion de las ventas
fechas = []
sucursales = []
productos = []
claves_producto = []
precios = []
cantidades_vendidas = []
totales_ticket = []

for i in range(1, 1001):
  ##############################################################################
  # 1. Generamos la informacion simulada
  ##############################################################################
  sucursal = r.choice(papelerias)
  producto = r.choice(lineas)
  clave_producto = r.choice(abcdario) + r.choice(abcdario) + r.choice(abcdario) + "-" + str(r.randint(1,9)) + str(r.randint(1,9)) + str(r.randint(1,9))
  precio = round(r.random() * r.randint(100, 10000), 2)
  cantidad_vendida = r.randint(1, 1000)
  total_ticket = precio * cantidad_vendida
  ##############################################################################
  # 2. La agregamos a nuestras listas vacias
  ##############################################################################
  fechas.append(fecha)
  sucursales.append(sucursal)
  productos.append(producto)
  claves_producto.append(clave_producto)
  precios.append(precio)
  cantidades_vendidas.append(cantidad_vendida)
  totales_ticket.append(total_ticket)

# Definimos el dataframe
import pandas as pd

# diccionario con la estructura del dataframe
diccionario_ventas_df = {
    "Fecha": fechas,
    "Sucursal": sucursales,
    "Producto": productos,
    "Clave_Producto": claves_producto,
    "Precio": precios,
    "Cantidad_Vendida": cantidades_vendidas,
    "Total_Ticket": totales_ticket
}

# Crearemos el dataframe
df_ventas = pd.DataFrame(diccionario_ventas_df)
df_ventas

,Fecha,Sucursal,Producto,Clave_Producto,Precio,Cantidad_Vendida,Total_Ticket
0,2025-01-04,Polanco,Audífonos,MYR-747,421.26,899,378712.74
1,2025-01-04,Centro,Cartulinas,MZQ-447,2816.94,837,2357778.78
2,2025-01-04,Xochimilco,Borradores,FXN-219,185.20,264,48892.80
3,2025-01-04,Santa Fé,Libretas,BWM-347,49.78,746,37135.88
4,2025-01-04,CU,Pc,RFL-414,1105.45,726,802556.70
...,...,...,...,...,...,...,...
995,2025-01-04,CU,Tijeras,UHX-418,1278.03,787,1005809.61
996,2025-01-04,Milpa Alta,Papel,ODL-396,5317.59,433,2302516.47
997,2025-01-04,Centro,Baterías,QMY-586,5411.20,717,3879830.40
998,2025-01-04,Xochimilco,Plumones,UYK-382,5033.16,328,1650876.48
999,2025-01-04,Milpa Alta,Cajas,ZAD-753,1643.53,73,119977.69

---

# 3. Introducción a SQL

Una vez que ya tenemos el dataframe, lo que haremos será crear tanto una base de datos como una tabla en SQL para posteriormente aliminarla con la información de ventas al 2025-01-05. Para ello:

### Creación de una BBDD y una tabla

Para poder trabajar con SQL mediante Python, haremos uso de la librería SQLITE

In [ ]:
import sqlite3 as sql

# codigo para crear la base de datos
# es importante que el nombre del archivo termine con .db
sql.connect("Prueba1.db")

Para poder crear nuestra primer tabla, primero debemos explorar un poco el origen de la información, el cual será el dataframe.

In [ ]:
# Exploraremos el dataframe como siguie:
# 1. Ver los nombres de las columnas
df_ventas.columns

Index(['Fecha', 'Sucursal', 'Producto', 'Clave_Producto', 'Precio',
       'Cantidad_Vendida', 'Total_Ticket'],
      dtype='object')

In [ ]:
# 2. Ver el tipo de datos de cada columna
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Fecha             1000 non-null   object
 1   Sucursal          1000 non-null   object
 2   Producto          1000 non-null   object
 3   Clave_Producto    1000 non-null   object
 4   Precio            1000 non-null   float64
 5   Cantidad_Vendida  1000 non-null   int64
 6   Total_Ticket      1000 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 54.8+ KB

Esto último nos será de gran utilidad para definir nuestra primer tabla en SQL.

Antes de ello, para usar código SQL en Python deberemos de hacerlo mediante strings multilínea de la siguiente forma

In [ ]:
# 1. Definimos el codigo SQL (mas adelante se explica con mas detalle)
codigo_sql = """
CREATE TABLE
  VENTAS_2025 (
    Fecha TEXT,
    Sucursal TEXT,
    Producto TEXT,
    Clave_Producto TEXT,
    Precio REAL,
    Cantidad_Vendida INTEGER,
    Total_Ticket REAL
  )

"""

# 2. Hacemos la conexion a la base de datos como sigue
con = sql.connect("Prueba1.db")

# 3. Definimos un puente entre Python y SQL con el cual podremos ejecutar sentencias SQL
cursor = con.cursor()

# 4. Ejecutamos el codigo SQL
cursor.execute(codigo_sql)

# 5. Guardamos cambios
con.commit()

# 6. Cerramos la conexion
con.close()

En general, la estructura anterior es la estructura con la cual estaremos ejecutando sentencias SQL.

Ahora, veamos cómo insertar información en nuestra tabla

In [ ]:
# Sentencia SQL
query_sql = """
INSERT INTO
  VENTAS_2025(
    Fecha,
    Sucursal,
    Producto,
    Precio,
    Cantidad_Vendida,
    Total_Ticket
    )
VALUES(
  '2024-01-05',
  'Xochimilco',
  'Libreta',
  24.00,
  7,
  168.00
)
"""

# 2. Hacemos la conexion a la base de datos como sigue
con = sql.connect("Prueba1.db")

# 3. Definimos un puente entre Python y SQL con el cual podremos ejecutar sentencias SQL
cursor = con.cursor()

# 4. Ejecutamos el codigo SQL
cursor.execute(query_sql)

# 5. Guardamos cambios
con.commit()

# 6. Cerramos la conexion
con.close()

Veamos la información insertada mediante una CONSULTA

In [ ]:
# Para ello usaremnos un comando de la libreria pandas
query_select = """
SELECT
  *
FROM
  VENTAS_2025
"""

# 2. Hacemos la conexion a la base de datos como sigue
con = sql.connect("Prueba1.db")

# 3. Definimos un puente entre Python y SQL con el cual podremos ejecutar sentencias SQL
# PARA REALIZAR CONSULTAS A LA BASE DE DATOS NO NECESITAMOS DEL CURSOR
# cursor = con.cursor()

# 4. Ejecutamos el codigo SQL
# EN CONSULTAS NO EJECUTAMOS SENTENCIAS COMO TAL A LA BASE DE DATOS
# cursor.execute(query_sql)

# 5. Guardamos cambios
# NO ES NECESARIO GUARDAR CAMBIOS EN LAS CONSULTAS
# con.commit()

################################################################################
# En su lugar, bastará con consultar la info a la base de datos
# y convertirla a un dataframe comom sigue
df = pd.read_sql(query_select, con)

# 6. Cerramos la conexion
# SIEMPRE QUE ABRAMOS UNA CONEXION A LA BASE DE DATOS, ES NECESARIO CERRARLA
con.close()

# Mandamos a imprimir el dataframe
df

,Fecha,Sucursal,Producto,Clave_Producto,Precio,Cantidad_Vendida,Total_Ticket
0,2024-01-05,Xochimilco,Libreta,None,24.0,7,168.0

### Inserciones múltiples

Ahora haremos uso de lo aprendido en cuanto a bucles y a la fucnión ``loc`` de pandas.

In [ ]:
# Con la funcion head() podemos ver solo las primeras 5 filas del dataframe
df_ventas.head()

,Fecha,Sucursal,Producto,Clave_Producto,Precio,Cantidad_Vendida,Total_Ticket
0,2025-01-04,Polanco,Audífonos,MYR-747,421.26,899,378712.74
1,2025-01-04,Centro,Cartulinas,MZQ-447,2816.94,837,2357778.78
2,2025-01-04,Xochimilco,Borradores,FXN-219,185.20,264,48892.80
3,2025-01-04,Santa Fé,Libretas,BWM-347,49.78,746,37135.88
4,2025-01-04,CU,Pc,RFL-414,1105.45,726,802556.70

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Fecha             1 non-null      object
 1   Sucursal          1 non-null      object
 2   Producto          1 non-null      object
 3   Clave_Producto    0 non-null      object
 4   Precio            1 non-null      float64
 5   Cantidad_Vendida  1 non-null      int64
 6   Total_Ticket      1 non-null      float64
dtypes: float64(2), int64(1), object(4)
memory usage: 184.0+ bytes

In [ ]:
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Fecha             1000 non-null   object
 1   Sucursal          1000 non-null   object
 2   Producto          1000 non-null   object
 3   Clave_Producto    1000 non-null   object
 4   Precio            1000 non-null   float64
 5   Cantidad_Vendida  1000 non-null   int64
 6   Total_Ticket      1000 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 54.8+ KB

In [ ]:
# 2. Hacemos la conexion a la base de datos como sigue
con = sql.connect("Prueba1.db")

cursor = con.cursor()

# Sentencia SQL, hacemos un f-string multilinea
for i in range(len(df_ventas)):
  query_sql = f"""
  INSERT INTO
    VENTAS_2025
  VALUES(
    -- Esto es un comentario en SQL
    -- Ojo con las comillas que colocamos, debido a que definimos las columnas
    -- como TEXT, es decir, como cadenas de texto
    '{df_ventas.loc[i, "Fecha"]}',
    '{df_ventas.loc[i, "Sucursal"]}',
    '{df_ventas.loc[i, "Producto"]}',
    '{df_ventas.loc[i, "Clave_Producto"]}',
    {df_ventas.loc[i, "Precio"]},
    {df_ventas.loc[i, "Cantidad_Vendida"]},
    {df_ventas.loc[i, "Total_Ticket"]}
  )
  """

  # 4. Ejecutamos el codigo SQL
  cursor.execute(query_sql)

  # 5. Guardamos cambios
  con.commit()

# 6. Cerramos la conexion
con.close()

In [ ]:
# Realicemos una consulta para ver la informacion
# Para ello usaremnos un comando de la libreria pandas
query_select = """
SELECT
  *
FROM
  VENTAS_2025
"""

# 2. Hacemos la conexion a la base de datos como sigue
con = sql.connect("Prueba1.db")
df = pd.read_sql(query_select, con)
con.close()

df

,Fecha,Sucursal,Producto,Clave_Producto,Precio,Cantidad_Vendida,Total_Ticket
0,2024-01-05,Xochimilco,Libreta,None,24.00,7,168.00
1,2025-01-04,Polanco,Audífonos,MYR-747,421.26,899,378712.74
2,2025-01-04,Centro,Cartulinas,MZQ-447,2816.94,837,2357778.78
3,2025-01-04,Xochimilco,Borradores,FXN-219,185.20,264,48892.80
4,2025-01-04,Santa Fé,Libretas,BWM-347,49.78,746,37135.88
...,...,...,...,...,...,...,...
996,2025-01-04,CU,Tijeras,UHX-418,1278.03,787,1005809.61
997,2025-01-04,Milpa Alta,Papel,ODL-396,5317.59,433,2302516.47
998,2025-01-04,Centro,Baterías,QMY-586,5411.20,717,3879830.40
999,2025-01-04,Xochimilco,Plumones,UYK-382,5033.16,328,1650876.48
1000,2025-01-04,Milpa Alta,Cajas,ZAD-753,1643.53,73,119977.69

# 4. Funciones en Python 👁️

# 5. Manejo de fechas 🗓️